export const JOB_MOCK_DATA = [
    { id: 1, job_name: 'Invoice Processing', process_name: 'AP Automation', category: 'Finance', status: 'Active', created_by: 'rahul.sharma' },
    { id: 2, job_name: 'PO Matching', process_name: 'AP Automation', category: 'Finance', status: 'Active', created_by: 'amit.kumar' },
    { id: 3, job_name: 'GL Reconciliation', process_name: 'GL Close', category: 'Finance', status: 'Disabled', created_by: 'vikas.singh' },
    { id: 4, job_name: 'Employee Onboarding', process_name: 'HR Workflow', category: 'HR', status: 'Active', created_by: 'rohit.verma' },
    { id: 5, job_name: 'Timesheet Approval', process_name: 'HR Workflow', category: 'HR', status: 'Active', created_by: 'sandeep.yadav' },
    { id: 6, job_name: 'Benefits Enrollment', process_name: 'HR Benefits', category: 'HR', status: 'Disabled', created_by: 'manish.patel' },
    { id: 7, job_name: 'Order Fulfillment', process_name: 'SCM Process', category: 'Operations', status: 'Active', created_by: 'anil.reddy' },
    { id: 8, job_name: 'Inventory Sync', process_name: 'SCM Process', category: 'Operations', status: 'Active', created_by: 'deepak.nair' },
    { id: 9, job_name: 'Shipping Label Gen', process_name: 'Logistics Bot', category: 'Operations', status: 'Active', created_by: 'naveen.kumar' },
    { id: 10, job_name: 'Warehouse Audit', process_name: 'Logistics Bot', category: 'Operations', status: 'Disabled', created_by: 'kiran.sharma' },

    { id: 11, job_name: 'Vendor Creation', process_name: 'Procurement Flow', category: 'Finance', status: 'Active', created_by: 'arun.jain' },
    { id: 12, job_name: 'Expense Validation', process_name: 'Expense Bot', category: 'Finance', status: 'Active', created_by: 'sunil.gupta' },
    { id: 13, job_name: 'Tax Calculation', process_name: 'Finance Engine', category: 'Finance', status: 'Disabled', created_by: 'rakesh.mishra' },
    { id: 14, job_name: 'Payroll Processing', process_name: 'Payroll Bot', category: 'HR', status: 'Active', created_by: 'mahesh.rao' },
    { id: 15, job_name: 'Leave Approval', process_name: 'HR Workflow', category: 'HR', status: 'Active', created_by: 'gopal.krishna' },
    { id: 16, job_name: 'Recruitment Screening', process_name: 'Hiring Bot', category: 'HR', status: 'Disabled', created_by: 'praveen.kumar' },
    { id: 17, job_name: 'Stock Update', process_name: 'Inventory Bot', category: 'Operations', status: 'Active', created_by: 'harish.reddy' },
    { id: 18, job_name: 'Order Validation', process_name: 'Order Bot', category: 'Operations', status: 'Active', created_by: 'suresh.naidu' },
    { id: 19, job_name: 'Delivery Tracking', process_name: 'Logistics Bot', category: 'Operations', status: 'Active', created_by: 'raghu.varma' },
    { id: 20, job_name: 'Fleet Management', process_name: 'Transport Bot', category: 'Operations', status: 'Disabled', created_by: 'venkat.rao' },

    // 30 female names
    { id: 21, job_name: 'Invoice Validation', process_name: 'AP Automation', category: 'Finance', status: 'Active', created_by: 'priya.sharma' },
    { id: 22, job_name: 'Budget Planning', process_name: 'Finance Engine', category: 'Finance', status: 'Active', created_by: 'neha.verma' },
    { id: 23, job_name: 'Cash Flow Analysis', process_name: 'Finance Engine', category: 'Finance', status: 'Disabled', created_by: 'pooja.gupta' },
    { id: 24, job_name: 'Employee Exit', process_name: 'HR Workflow', category: 'HR', status: 'Active', created_by: 'swathi.reddy' },
    { id: 25, job_name: 'Performance Review', process_name: 'HR Workflow', category: 'HR', status: 'Active', created_by: 'kavya.nair' },
    { id: 26, job_name: 'Training Assignment', process_name: 'HR Learning', category: 'HR', status: 'Disabled', created_by: 'anita.iyer' },
    { id: 27, job_name: 'Procurement Request', process_name: 'SCM Process', category: 'Operations', status: 'Active', created_by: 'divya.bansal' },
    { id: 28, job_name: 'Supplier Sync', process_name: 'SCM Process', category: 'Operations', status: 'Active', created_by: 'meena.kumari' },
    { id: 29, job_name: 'Route Optimization', process_name: 'Logistics Bot', category: 'Operations', status: 'Active', created_by: 'rekha.pillai' },
    { id: 30, job_name: 'Dispatch Planning', process_name: 'Transport Bot', category: 'Operations', status: 'Disabled', created_by: 'shilpa.shetty' },

    { id: 31, job_name: 'Payment Processing', process_name: 'AP Automation', category: 'Finance', status: 'Active', created_by: 'lakshmi.reddy' },
    { id: 32, job_name: 'Fraud Detection', process_name: 'Finance AI', category: 'Finance', status: 'Active', created_by: 'sneha.iyer' },
    { id: 33, job_name: 'Ledger Posting', process_name: 'GL Close', category: 'Finance', status: 'Disabled', created_by: 'archana.sharma' },
    { id: 34, job_name: 'Offer Letter Gen', process_name: 'Hiring Bot', category: 'HR', status: 'Active', created_by: 'deepa.nair' },
    { id: 35, job_name: 'Attendance Sync', process_name: 'HR System', category: 'HR', status: 'Active', created_by: 'sarika.jain' },
    { id: 36, job_name: 'Policy Update', process_name: 'HR Governance', category: 'HR', status: 'Disabled', created_by: 'ritu.singh' },
    { id: 37, job_name: 'Demand Forecasting', process_name: 'SCM AI', category: 'Operations', status: 'Active', created_by: 'aishwarya.rao' },
    { id: 38, job_name: 'Stock Allocation', process_name: 'Inventory Bot', category: 'Operations', status: 'Active', created_by: 'bhavana.reddy' },
    { id: 39, job_name: 'Shipment Booking', process_name: 'Logistics Bot', category: 'Operations', status: 'Active', created_by: 'harini.krishna' },
    { id: 40, job_name: 'Vehicle Assignment', process_name: 'Transport Bot', category: 'Operations', status: 'Disabled', created_by: 'keerthi.nair' },

    { id: 41, job_name: 'Audit Logging', process_name: 'Compliance Bot', category: 'Finance', status: 'Active', created_by: 'nisha.patel' },
    { id: 42, job_name: 'Risk Assessment', process_name: 'Finance AI', category: 'Finance', status: 'Active', created_by: 'preeti.singh' },
    { id: 43, job_name: 'Closing Entries', process_name: 'GL Close', category: 'Finance', status: 'Disabled', created_by: 'sonal.gupta' },
    { id: 44, job_name: 'Employee Survey', process_name: 'HR Engagement', category: 'HR', status: 'Active', created_by: 'anjali.mehta' },
    { id: 45, job_name: 'Shift Scheduling', process_name: 'HR System', category: 'HR', status: 'Active', created_by: 'pallavi.joshi' },
    { id: 46, job_name: 'Exit Interview', process_name: 'HR Workflow', category: 'HR', status: 'Disabled', created_by: 'komal.verma' },
    { id: 47, job_name: 'Order Dispatch', process_name: 'SCM Process', category: 'Operations', status: 'Active', created_by: 'shweta.mishra' },
    { id: 48, job_name: 'Inventory Audit', process_name: 'Inventory Bot', category: 'Operations', status: 'Active', created_by: 'tanvi.sharma' },
    { id: 49, job_name: 'Delivery Confirmation', process_name: 'Logistics Bot', category: 'Operations', status: 'Active', created_by: 'vaishnavi.reddy' },
    { id: 50, job_name: 'Transport Billing', process_name: 'Transport Bot', category: 'Operations', status: 'Disabled', created_by: 'poornima.nair' },
];